default_job = "clippy"

[jobs.clippy]
command = [
    "cargo", "clippy",
    "--tests",
    "--color", "always",
    "--",
    "-Wclippy::pedantic",
    "-A", "clippy::missing_errors_doc", # temporarily allowed until we close XCVM-240
]
need_stdout = false