[workspace]
members = ["vm", "vm-wasmi", "orchestrate"]
exclude = ["fixtures/recursion-test"]
resolver = "2"


[workspace.dependencies]
cosmwasm-std = { git = "https://github.com/dzmitry-lahoda-forks/cosmwasm", rev = "f483c3c4695fcb094539b5aead223d54cb0e23b2", default-features = false, features = [
  "iterator",
  "cosmwasm_1_2",
] }
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
log = { version = "0.4", default-features = false }
num = { version = "0.4", default-features = false }