[toolchain]
channel = "nightly-2022-08-09"
components = [
  "clippy",
  "llvm-tools-preview",
  "rust-analyzer",
  "rustfmt",
  "rust-src",
]
targets = ["thumbv7em-none-eabi", "wasm32-unknown-unknown"]
